### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AsaiToshiya** [MichaelHolley/Vid2JPG#2]
Can you please tell me what is the license of this repo?

**Comment by MichaelHolley** [comment]
> Can you please tell me what is the license of this repo?

Sorry for replying so late. I am not that familiar with all the types of licenses out there.
Feel free to use this code for whatever you want. Mentioning me is nice to have but not required.

**Comment by AsaiToshiya** [comment]
Thank you for your reply, great software and the generous license.
